# Generated by Django 4.0.3 on 2022-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='m_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='retail',
            field=models.IntegerField(default=0),
        ),
    ]
