# Generated by Django 4.0.3 on 2022-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_view', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
