# Generated by Django 4.0.3 on 2022-05-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_view', '0007_remove_order_cash_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_memo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_view.cashmemo'),
            preserve_default=False,
        ),
    ]
