# Generated by Django 4.0.3 on 2022-05-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_view', '0011_order_cash_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmemo',
            name='cart_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_view.cart'),
            preserve_default=False,
        ),
    ]
