# Generated by Django 4.0.3 on 2022-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_view', '0013_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='restriction',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
